name: CI

on:
  push:
    branches: [master]
    # paths:
    #   - grammar.js
    #   - src/**
    #   - test/**
    #   - bindings/**
    #   - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    #runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          abi_version: [14, 15]
    #     os: [ubuntu-latest, windows-latest, macos-14]
    env:
      TREE_SITTER_ABI_VERSION: ${{ matrix.abi_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Install dependencies
        run: npm ci --omit dev --omit peer --omit optional
      # - name: Verify parser
      #   run: git diff --exit-code -- src/parser.c
      - name: Test parser
        uses: tree-sitter/parser-test-action@v2
        with:
          test-parser: true
      - name: Test python binding
        uses: tree-sitter/parser-test-action@v2
        with:
          test-python: true
      - name: Test other binding
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
          test-node: true
          test-go: true
          test-swift: true
      - name: Generate parser 14
        if: ${{ matrix.abi_version != 15 }}
        run: |
          tree-sitter generate --abi=${{ matrix.abi_version }}
          [[ ! -d node_modules ]] || rm -rf node_modules
      - name: Generate parser 15
        uses: tree-sitter/parser-test-action@v2
        with:
          test-parser: false
          generate: ${{ matrix.abi_version == 15 }}
      # - name: Generate parser
      #   if: ${{ matrix.abi_version != 15 }}
      #   run: tree-sitter generate --abi=${{ matrix.abi_version }}
      # - name: Parse examples
      #   uses: tree-sitter/parse-action@v4
      #   with:
      #     files: examples/*
